#pragma once

static const char *index_html = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<title>ESP32-S3 Provisioning</title>"
"<style>"
"body { font-family: Arial, sans-serif; margin: 20px; }"
"input[type=text], input[type=password] { width: 100%; padding: 12px 20px; margin: 8px 0; display: inline-block; border: 1px solid #ccc; box-sizing: border-box; }"
"button { background-color: #4CAF50; color: white; padding: 14px 20px; margin: 8px 0; border: none; cursor: pointer; width: 100%; }"
"button:hover { opacity: 0.8; }"
".container { padding: 16px; }"
".usb-container { padding: 16px; margin-top: 20px; border-top: 1px solid #ccc; }"
"</style>"
"<script>"
"function subUsb(e) {"
"  e.preventDefault();"
"  var v = document.getElementById('usb_input').value;"
"  var x = new XMLHttpRequest();"
"  x.open('POST', '/save_usb', true);"
"  x.onload = function() {"
"    if (x.status == 200) {"
"      document.open();"
"      document.write(x.responseText);"
"      document.close();"
"    }"
"  };"
"  x.send(v);"
"}"
"</script>"
"</head>"
"<body>"
"<h2>Connect ESP32 to WiFi</h2>"
"<form action=\"/connect\" method=\"post\">"
"  <div class=\"container\">"
"    <label for=\"ssid\"><b>SSID</b></label>"
"    <input type=\"text\" placeholder=\"Enter WiFi SSID\" name=\"ssid\" required>"
"    <label for=\"psw\"><b>Password</b></label>"
"    <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" required>"
"    <button type=\"submit\">Connect WiFi</button>"
"  </div>"
"</form>"
"<div class=\"usb-container\">"
"<h2>USB Keyboard Settings</h2>"
"<form onsubmit=\"subUsb(event)\">"
"  <div class=\"container\">"
"    <label for=\"usb_str\"><b>USB Keyboard String</b></label>"
"    <textarea id=\"usb_input\" placeholder=\"Enter String to Type\" name=\"usb_str\" maxlength=\"1024\" rows=\"5\" style=\"width: 100%; padding: 12px 20px; margin: 8px 0; display: inline-block; border: 1px solid #ccc; box-sizing: border-box;\" required></textarea>"
"    <button type=\"submit\" style=\"background-color: #008CBA;\">Save USB String</button>"
"  </div>"
"</form>"
"</div>"
"<div class=\"usb-container\">"
"<h2>Shared Clipboard</h2>"
"<p>Share content with all connected devices</p>"
"<a href=\"/clipboard\"><button style=\"background-color: #FF9800;\">Open Shared Clipboard</button></a>"
"</div>"
"</body>"
"</html>";

static const char *usb_saved_html = 
"<!DOCTYPE html>"
"<html>"
"<body>"
"<h2>USB String Saved</h2>"
"<p>The string for USB keyboard simulation has been updated.</p>"
"<a href=\"/\"><button style=\"width: auto;\">Back</button></a>"
"</body>"
"</html>";

static const char *success_html = 
"<!DOCTYPE html>"
"<html>"
"<body>"
"<h2>Credentials Received</h2>"
"<p>ESP32 is attempting to connect...</p>"
"</body>"
"</html>";

static const char *clipboard_html_template = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<title>Shared Clipboard</title>"
"<script>"
"var initialContent = '%s';" // %s for base64 content
"function utf8ToString(base64) {"
"  try {"
"    var binary = atob(base64);"
"    var bytes = new Uint8Array(binary.length);"
"    for (var i = 0; i < binary.length; i++) {"
"      bytes[i] = binary.charCodeAt(i);"
"    }"
"    var decoder = new TextDecoder('utf-8');"
"    return decoder.decode(bytes);"
"  } catch(e) {"
"    console.log('Error:', e);"
"    return '';"
"  }"
"}"
"function stringToUtf8Base64(str) {"
"  return window.btoa(unescape(encodeURIComponent(str)));"
"}"
"var ws = null;"
"var shareButton = null;"
"var statusIndicator = null;"
"function connectWebSocket() {"
"  updateStatus('Connecting...');"
"  disableShareButton();"
"  "
"  var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';"
"  var wsUrl = protocol + '//' + window.location.host + '/ws';"
"  ws = new WebSocket(wsUrl);"
"  "
"  ws.onopen = function() {"
"    console.log('WebSocket connected');"
"    updateStatus('Connected');"
"    enableShareButton();"
"    try {"
"      ws.send(JSON.stringify({type: 'get_state'}));"
"    } catch (e) {"
"      console.log('Send error:', e);"
"      updateStatus('Send Error: ' + e.message);"
"    }"
"  };"
"  "
"  ws.onmessage = function(event) {"
"    try {"
"      var msg = JSON.parse(event.data);"
"      if (msg.type === 'update' && msg.content) {"
"        var content = utf8ToString(msg.content);"
"        var textarea = document.getElementById('clipboardContent');"
"        if (textarea.value !== content) {"
"          textarea.value = content;"
"        }"
"      }"
"    } catch(e) {"
"      console.log('Error processing WebSocket message:', e);"
"    }"
"  };"
"  "
"  ws.onclose = function() {"
"    console.log('WebSocket disconnected, reconnecting...');"
"    updateStatus('Disconnected - Reconnecting...');"
"    disableShareButton();"
"    setTimeout(connectWebSocket, 2000);"
"  };"
"  "
"  ws.onerror = function(error) {"
"    console.log('WebSocket error:', error);"
"    updateStatus('Connection Error');"
"  };"
"}"
"function updateStatus(message) {"
"  var el = document.getElementById('statusIndicator');"
"  if (el) {"
"    el.textContent = message;"
"    if (message === 'Connected') el.style.color = 'green';"
"    else if (message.indexOf('Error') !== -1 || message.indexOf('Disconnected') !== -1) el.style.color = 'red';"
"    else el.style.color = '#666';"
"  }"
"}"
"function enableShareButton() {"
"  if (shareButton) {"
"    shareButton.disabled = false;"
"  }"
"}"
"function disableShareButton() {"
"  if (shareButton) {"
"    shareButton.disabled = true;"
"  }"
"}"
"function sendUpdate(event) {"
"  if (ws && ws.readyState === WebSocket.OPEN) {"
"    event.preventDefault();"
"    var content = document.getElementById('clipboardContent').value;"
"    var base64 = stringToUtf8Base64(content);"
"    var msg = {type: 'update', content: base64};"
"    ws.send(JSON.stringify(msg));"
"    console.log('Sent update via WebSocket');"
"    return false;"
"  }"
"  return true;"
"}"
"function copyContent() {"
"  var copyText = document.getElementById(\"clipboardContent\");"
"  copyText.select();"
"  copyText.setSelectionRange(0, 99999); /* For mobile devices */"
"  try {"
"    var successful = document.execCommand('copy');"
"    var msg = successful ? 'Copied!' : 'Copy failed';"
"    updateStatus(msg);"
"    setTimeout(function() { "
"       if(ws && ws.readyState === WebSocket.OPEN) updateStatus(\"Connected\"); "
"    }, 2000);"
"  } catch (err) {"
"    console.log('Unable to copy');"
"    updateStatus(\"Copy failed\");"
"  }"
"}"
"function clearContent() {"
"  var textarea = document.getElementById('clipboardContent');"
"  textarea.value = '';"
"}"
"window.onload = function() {"
"  var textarea = document.getElementById('clipboardContent');"
"  shareButton = document.getElementById('shareButton');"
"  statusIndicator = document.getElementById('statusIndicator');"
"  "
"  if (initialContent) {"
"    textarea.value = utf8ToString(initialContent);"
"  }"
"  "
"  connectWebSocket();"
"  };"
"</script>"
"</head>"
"<body>"
"<h2>Shared Clipboard</h2>"
"<p id=\"statusIndicator\" style=\"color: #666;\">Connecting...</p>"
"<p>Share content with all connected devices</p>"
"<form onsubmit=\"return sendUpdate(event)\">"
"  <div class=\"container\">"
"    <label for=\"content\"><b>Content (Max 1024 chars)</b></label>"
"    <textarea id=\"clipboardContent\" name=\"content\" maxlength=\"1024\" rows=\"5\" style=\"width: 100%%; padding: 12px 20px; margin: 8px 0; display: inline-block; border: 1px solid #ccc; box-sizing: border-box;\"></textarea>"
"    <div style=\"display: flex; gap: 10px;\">"
"      <button id=\"shareButton\" type=\"submit\" style=\"background-color: #4CAF50; flex: 1;\" disabled>Share</button>"
"      <button type=\"button\" onclick=\"copyContent()\" style=\"background-color: #2196F3; flex: 1;\">Copy</button>"
"      <button type=\"button\" onclick=\"clearContent()\" style=\"background-color: #f44336; flex: 1;\">Clear</button>"
"    </div>"
"  </div>"
"</form>"
"<a href=\"/\"><button style=\"background-color: #008CBA; width: auto;\">Back</button></a>"
"</body>"
"</html>";

